fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: check-json
      exclude: .vscode
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: \.(bin|obj|dat|hex|raw|a|o)$

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v16.0.2'
  hooks:
    - id: clang-format
      exclude_types: [javascript, json]
      files: \.(h|hpp|c|cpp|cc|cxx)$
      exclude: ^(build/|external/|third_party/)

- repo: https://github.com/cheshirekow/cmake-format
  rev: v0.6.13
  hooks:
    - id: cmake-format
      files: ^(CMakeLists\.txt|.*\.cmake)$

- repo: local
  hooks:
    - id: clang-tidy
      name: clang-tidy
      entry: clang-tidy
      language: system
      types: [c, cpp]
      files: \.(h|hpp|c|cpp|cc|cxx)$
      exclude: ^(build/|external/|third_party/)
