function(add_sanitizer_flags enable_sanitize_addr enable_sanitize_undef)
    if (NOT enable_sanitize_addr AND NOT enable_sanitize_undef)
        message(STATUS "Sanitizers deactivated.")
        return()
    endif()

    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID MATCHES "GNU")
        add_compile_options("-fno-omit-frame-pointer")
        add_link_options("-fno-omit-frame-pointer")

        if(enable_sanitize_addr)
            add_compile_options("-fsanitize=address")
            add_link_options("-fsanitize=address")
        endif()

        if(enable_sanitize_undef)
            add_compile_options("-fsanitize=undefined")
            add_link_options("-fsanitize=undefined")
        endif()

        if(ENABLE_THREAD_SANITIZER)
            add_compile_options("-fsanitize=thread")
            add_link_options("-fsanitize=thread")
            message(STATUS "Thread sanitizer enabled")
        else()
            message(STATUS "Thread sanitizer not enabled")
        endif()

    elseif(CMAKE_CXX_COMPILER_ID MATCHES "MSVC")
        if(enable_sanitize_addr)
            add_compile_options("/fsanitize=address")
        endif()

        if(enable_sanitize_undef)
            message(STATUS "Undefined sanitizer not impl. for MSVC!")
        endif()
    else()
        message(STATUS "Sanitizer not supported in this environment!")
    endif()
endfunction(add_sanitizer_flags)
