
name: Ubuntu CI Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        preset: [debug, release]  # Test both build types
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y ninja-build && pip install -U gcovr

      - name: Configure
        run: cmake --preset ${{ matrix.preset }}

      - name: Build
        run: cmake --build --preset ${{ matrix.preset }}-build --parallel $(nproc)

      - name: Run Tests (Debug only)
        if: matrix.preset == 'debug'
        run: ctest --preset test

      - name: Code Coverage (Debug only)
        if: matrix.preset == 'debug'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/coverage/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          thresholds: '60 80'

      - name: Add Coverage PR Comment
        if: matrix.preset == 'debug' && github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.preset }}
          path: build/
